version: "3.0"

services:
    client:
      build: ./client
      restart: always
      ports:
        - "80:3000"
      volumes:
        - ./client:/client
        - /client/node_modules
      links:
        - server
      networks:
        - webappnetwork
    server:
      build: ./server
      restart: always
      ports:
        - "9999:9999"
      env_file: ./server/.env
      volumes:
        - ./server:/server
        - /server/node_modules
      depends_on:
        - db
      # links:
      #   - db
      networks:
        - webappnetwork
    db:
      image: mysql:5.7
      volumes:
        - ./db/mysql/data:/var/lib/mysql
      restart: always
      ports:
        - "3333:3306"
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: file_manager
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      networks:
        - webappnetwork

networks:
  webappnetwork:
      driver: bridge

volumes:
  db_data: {}